{
  "chumi": "chumi.webp",
  "chumi do": "chumi.webp",
  "aly": "cute.webp",
  "love you": "huh.webp",
  "ruk": "huh.webp",
  "dj": "huh.webp",
  "bisma": "huh.webp",
  "bahi": "huh.webp",
  "bhabhi": "huh.webp",
  "handsome": "huh.webp",
  "bhai": "huh.webp",
  "mela bacha": "cute.webp",
  "bubu": "cute.webp",
  "babu": "cute.webp",
  "aww": "cute.webp",
  "baby": "cute.webp",
  "janam": "cute.webp",
  "jan": "cute.webp",
  "jawad": "ayain.webp",
  "khan": "ayain.webp",
  "hi": "hello.webp",
  "hello": "hello.webp",
  "oye": "hello.webp",
  "bye": "hello.webp",
  "ayain": "ayain.webp"
}